image: archlinux
secrets:
- b64778ba-0b5e-49b2-9f75-0d9a79d34fbf
packages:
  - go
sources:
  - https://github.com/go-ap/handlers
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd handlers && go mod download
  - tests: |
      cd handlers && make test
  - coverage: |
      set -a +x
      cd handlers && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @handlers.coverprofile \
          -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${HANDLERS_TOKEN}&branch=${GIT_BRANCH}&service=custom"
