image: archlinux
secrets:
- 72c9ab0b-ed5f-4291-bab7-30b361be94a6
packages:
  - go
sources:
  - https://github.com/go-ap/activitypub
environment:
  GO111MODULE: 'on'
tasks:
  - install_go_tip: |
      go install golang.org/dl/gotip@latest
      export PATH=$PATH:$(go env GOPATH)/bin
      gotip download
  - tests: |
      cd activitypub
      export PATH=$PATH:$(go env GOPATH)/bin
      export GO=gotip
      gotip mod tidy
      make test
  - coverage: |
      set -a +x
      export PATH=$PATH:$(go env GOPATH)/bin
      export GO=gotip
      cd activitypub && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @activitypub.coverprofile \
           -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${PUB_TOKEN}&branch=${GIT_BRANCH}&service=custom" || true
