image: archlinux
packages:
  - go
  - postgresql
sources:
  - https://github.com/go-ap/activitystreams
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd activitystreams && go mod download
  - tests: |
      cd activitystreams
      go test -v ./...
