language: go

go:
- "1.10"
- "tip"

env:
  secure: C8I+rscEro6XAxnKy4AD2L474qr2r1oEurXR7o33OvAe9kFqumPWo+1auCP2TfShn3ZzDvydEMyW0lfztmujeVKDN9xIrP0KAMC19gFV4AeBGRHJDokPuhwFIQAT0qAEbHNR0ktMU6hC6dXRJKu9VHJ0iGnLor2k3VRgIFEj/21kFUaxN4sAGGh07/MWCa24+SOCpYtseSFLXR6eY/wlMu1W5NcwcOsnRSG8nn3TjfFnyWYmu56qUDuWkdCBFDRkC8mtclsepjeo6SYCwrZlYlbZoux+kWllfFJGQ/EDIejNPOjz5kSAfz2d27/szRMHRr+xGUJ3J236OCAGpQDUoaGfXY9aw/AKqqgVdsPrhXmjuC/OzGKx1ljCPN5bLjcrDu1c6JE1pxKek1+UCPQynEfZ/yqlLf1mhTEpqqlrfj/bCxnABsxFw8gQFYSdsHL13iq0Ll+zdOsEq5WuJVoNekWM2VtARLStq0F1L769UhERtZzIo/QxNe6X/B1OVuWfqDIeDZSZJuYAkWtkhVjtLFnAY/bGvhhG/SW97o8bvpXNfNYOWQR+wyspfnZQyZK2coUeG5wTrFDF7SwedAST4rEqojNteDvSAqOy23H7AvVlt6Ac95rrHetA5Fd+gbO04lQVYEgyhTHneFnnu5q4Mr215FrlhbSia6/JeSQxOLw=

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get -u github.com/dave/courtney
- go get github.com/mattn/goveralls
- GOPATH=$GOPATH:$(pwd) go get -t -v ./...

script:
- GOPATH=$GOPATH:$(pwd) go test -v ./...

after_success:
- GOPATH=$GOPATH:$(pwd) go test -coverprofile coverage.out -coverpkg activitypub,jsonld ./...
- GOPATH=$GOPATH:$(pwd) $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
