language: go

go:
- '1.10'
- 'tip'

env:
  secure: ZWPheXMN8k1Bpb4VnRDo/1ZZ5o3c3jmGUJRIaR2eBnVjSHoilNBdiZCTDbGbyFA9VP7OLEPUxKDewB1ELU556MIXKCjjFzm3ewyXNG0M4AwC++hfXuCD4qvlmH4LWleKD5dILCA5W5iwHCO2P1E/XXXp61KXxn9K16I4dJiJliSqN2/qQV3XjUrd3NlxOw6E6RNM3JSeYLU/MsrAXfXNG5L6uowtRKjVGZd00aivPNeb6CnUhRoGFmEqiOeX9SVDnKhaGbFe8aOiGFjRMWRHlFk1UDjmBAiKOB77jU8gCsLZKZgkDZ0LYAIElrTvk5WPwUGKcai4o7zS3heBPLjHpyniEfM4Ym4MkA8X8a/avd4Kc8fM0WC3BIaoRpeMQNu8uh0RGUt7cCF6YWFgejSHCf7heMqIjZcTS9t92CWKH5EOf2TVQp02YhHICkPO9J7pSQ0dvYF61tBp+yCmtgeraxZ4PSqSf6oCKbjiKGjWe1UCAn+L1GkAepioRmXyOGTQLR7vFk/EC35n8XTM4i3/3U3tZ6e4OCXzMT+qNFrmtSyuJbv4OkK5wPbP4JcMLw4hTGhULncD4fI7COqmlNkaCdT1gSOPugjgLXjon4YzpzBsntA/ivzwNUSCPWrj/NfCVKDH9m6GN2Y7Qtz8CwDP/hpDJrKiyu6CwuWHdpDEObI=
matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get -u github.com/dave/courtney
- go get github.com/mattn/goveralls
- go get github.com/modocache/gover
- GOPATH=$GOPATH:$(pwd) go get -t -v ./...

script:
- GOPATH=$GOPATH:$(pwd) go test -v ./...

after_success:
- GOPATH=$GOPATH:$(pwd) go test -cover ./...
- GOPATH=$GOPATH:$(pwd) $GOPATH/bin/gover
- GOPATH=$GOPATH:$(pwd) $GOPATH/bin/goveralls -coverprofile gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
